apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- patches/pdb.yaml
patches:
- path: patches/replicas.patch.yaml
- path: patches/hpa.patch.yaml
- path: patches/rollingupdate.patch.yaml
- path: patches/prodlike.labels-env.patch.yaml
- path: patches/securitycontext.patch.yaml
images:
- name: OPSDESK_API_IMAGE
  newName: opsdesk/api
  newTag: 49d6b65-dirty
- name: OPSDESK_FRONTEND_IMAGE
  newName: opsdesk/frontend
  newTag: 49d6b65-dirty
- name: OPSDESK_WORKER_IMAGE
  newName: opsdesk/worker
  newTag: 49d6b65-dirty
