apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opsdesk-empty
  namespace: opsdesk
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opsdesk-empty
  namespace: opsdesk
subjects:
  - kind: ServiceAccount
    name: sa-api
  - kind: ServiceAccount
    name: sa-worker
  - kind: ServiceAccount
    name: sa-frontend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opsdesk-empty
