apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: opsdesk
spec:
  replicas: 1
  selector:
    matchLabels: { app: redis }
  template:
    metadata:
      labels: { app: redis }
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["sh","-lc","redis-cli ping | grep PONG"]
            initialDelaySeconds: 3
            periodSeconds: 5
