apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-api
  namespace: opsdesk
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-worker
  namespace: opsdesk
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-frontend
  namespace: opsdesk
automountServiceAccountToken: false
