apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: OPSDESK_API_IMAGE
  newName: opsdesk/api
  newTag: 73f4691-dirty
- name: OPSDESK_FRONTEND_IMAGE
  newName: opsdesk/frontend
  newTag: 73f4691-dirty
- name: OPSDESK_WORKER_IMAGE
  newName: opsdesk/worker
  newTag: 73f4691-dirty
